# Generated by Django 3.1 on 2020-08-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=45)),
                ('national_id', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_phone', models.CharField(max_length=11, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('university', models.CharField(max_length=80)),
                ('university_subject', models.CharField(max_length=50)),
                ('university_degree', models.CharField(choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('senior', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=15)),
                ('work_reputations', models.TextField(blank=True, null=True)),
                ('altium_designer', models.BooleanField(blank=True, default=False)),
                ('arduino', models.BooleanField(blank=True, default=False)),
                ('code_vision', models.BooleanField(blank=True, default=False)),
                ('proteus', models.BooleanField(blank=True, default=False)),
                ('atmel_studio', models.BooleanField(blank=True, default=False)),
                ('micro_controller', models.BooleanField(blank=True, default=False)),
                ('power', models.BooleanField(blank=True, default=False, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('expected_salary', models.FloatField(blank=True, null=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronics.fileupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
