# Generated by Django 3.1 on 2020-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicapplicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='tmp/resume'),
        ),
    ]
