# Generated by Django 3.1 on 2020-08-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_auto_20200811_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
